import type { OAExampleObject } from '../../types'
import type { OAProperty } from '../parser/getSchemaUi'
import { getSchemaUiFormUrlEncoded } from './getSchemaUiFormUrlEncoded'
import { getSchemaUiJson } from './getSchemaUiJson'
import { getSchemaUiXml } from './getSchemaUiXml'

interface ContentTypeSchemaExample {
  key: string
  summary: string
  valueGenerator: (uiProperties: OAProperty[] | OAProperty, useExample: boolean) => any
  lang?: string
}

function getContentTypeSchemaExample(contentType: string): ContentTypeSchemaExample {
  if (isXml(contentType)) {
    return {
      key: 'XML',
      summary: 'XML',
      valueGenerator: getSchemaUiXml,
      lang: 'xml',
    }
  }

  if (isFormUrlEncoded(contentType)) {
    return {
      key: 'Form URL-Encoded',
      summary: 'Form URL-Encoded',
      valueGenerator: getSchemaUiFormUrlEncoded,
      lang: 'plain',
    }
  }

  return {
    key: 'JSON',
    summary: 'JSON',
    valueGenerator: getSchemaUiJson,
    lang: 'json',
  }
}

export function getSchemaExample(contentType: string, uiProperties: OAProperty[] | OAProperty, useExample = false): Record<string, OAExampleObject> {
  const contentTypeSchemaExample = getContentTypeSchemaExample(contentType)
  return {
    [contentTypeSchemaExample.key]: getSchemaExampleValue(contentTypeSchemaExample, uiProperties, useExample),
  }
}

function getSchemaExampleValue(contentTypeSchema: ContentTypeSchemaExample, uiProperties: OAProperty[] | OAProperty, useExample = false): OAExampleObject {
  return {
    summary: contentTypeSchema.summary,
    description: '',
    value: contentTypeSchema.valueGenerator(uiProperties, useExample),
    isAutogenerated: true,
    lang: contentTypeSchema.lang ?? 'json',
  } as OAExampleObject
}

function isXml(contentType: string): boolean {
  return contentType.toLowerCase().match(/^(text|application)\/.*xml($|;|\\+)/) !== null
}

function isFormUrlEncoded(contentType: string): boolean {
  return contentType.toLowerCase().match(/^application\/x-www-form-urlencoded($|;|\\+)/) !== null
}
