<script setup>
import { computed } from 'vue'
import { useTheme } from '../../composables/useTheme'
import OACodeBlock from '../Common/OACodeBlock.vue'
import OAMarkdown from '../Common/OAMarkdown.vue'
import OASchemaUI from '../Schema/OASchemaUI.vue'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '../ui/tabs'

const props = defineProps({
  schema: {
    type: Object,
    required: true,
  },
  examples: {
    type: null,
    required: false,
  },
  defaultView: {
    type: String,
    required: false,
  },
})

const schemaViewerDeep = useTheme().getSchemaViewerDeep()

const defaultValue = computed(() => {
  const examplesKeys = Object.keys(props.examples ?? {})

  const viewMap = {
    schema: 'schema',
    contentType: examplesKeys?.length ? `examples.${examplesKeys[0]}` : 'schema',
    autogenerated: (() => {
      const autogeneratedExample = examplesKeys.find(key => props.examples[key]?.isAutogenerated)
      return autogeneratedExample ? `examples.${autogeneratedExample}` : 'schema'
    })(),
  }

  return viewMap[props.defaultView] ?? props.defaultView
})
</script>

<template>
  <Tabs
    :default-value="defaultValue"
  >
    <TabsList class="relative flex flex-row justify-start">
      <TabsTrigger
        value="schema"
        variant="schemaTabs"
        class="h-full"
      >
        {{ $t('Schema') }}
      </TabsTrigger>
      <TabsTrigger
        v-for="(_, exampleKey) in props.examples ?? {}"
        :key="exampleKey"
        :value="`examples.${exampleKey}`"
        variant="schemaTabs"
        class="h-full"
      >
        {{ exampleKey }}
      </TabsTrigger>
    </TabsList>
    <TabsContent value="schema">
      <div class="flex flex-col gap-2">
        <OASchemaUI
          :property="props.schema"
          :schema="props.schema"
          :deep="schemaViewerDeep"
        />
      </div>
    </TabsContent>
    <TabsContent
      v-for="(example, exampleKey) in props.examples ?? {}"
      :key="exampleKey"
      :value="`examples.${exampleKey}`"
    >
      <div class="flex flex-col gap-2">
        <OAMarkdown
          v-if="example?.description"
          :content="example?.description"
        />

        <OACodeBlock
          v-if="example?.value"
          :code="example?.value"
          :lang="example?.lang ?? 'json'"
          :label="(example?.lang ?? 'json').toUpperCase()"
          class="!m-0"
        />
      </div>
    </TabsContent>
  </Tabs>
</template>
