import { defineAsyncComponent } from 'vue'

export const OAVueJsonPretty = defineAsyncComponent(() => import('./Common/Highlight/OAVueJsonPretty.vue'))
export const OAHeading = defineAsyncComponent(() => import('./Common/OAHeading.vue'))
export const OAMarkdown = defineAsyncComponent(() => import('./Common/OAMarkdown.vue'))
export const OAInfo = defineAsyncComponent(() => import('./Feature/OAInfo.vue'))
export const OAIntroduction = defineAsyncComponent(() => import('./Feature/OAIntroduction.vue'))
export const OALocaleSelect = defineAsyncComponent(() => import('./Feature/OALocaleSelect.vue'))
export const OAOperation = defineAsyncComponent(() => import('./Feature/OAOperation.vue'))
export const OAOperationContext = defineAsyncComponent(() => import('./Feature/OAOperationContext.vue'))
export const OAOperationLink = defineAsyncComponent(() => import('./Feature/OAOperationLink.vue'))
export const OAServers = defineAsyncComponent(() => import('./Feature/OAServers.vue'))
export const OASpec = defineAsyncComponent(() => import('./Feature/OASpec.vue'))
export const OASpecSkeleton = defineAsyncComponent(() => import('./Feature/OASpecSkeleton.vue'))
export const OAParameter = defineAsyncComponent(() => import('./Parameter/OAParameter.vue'))
export const OAParameters = defineAsyncComponent(() => import('./Parameter/OAParameters.vue'))
export const OAPathEndpoint = defineAsyncComponent(() => import('./Path/OAPathEndpoint.vue'))
export const OAPlayground = defineAsyncComponent(() => import('./Playground/OAPlayground.vue'))
export const OARequestBody = defineAsyncComponent(() => import('./Request/OARequestBody.vue'))
export const OAResponses = defineAsyncComponent(() => import('./Response/OAResponses.vue'))
export const OACodeSamples = defineAsyncComponent(() => import('./Sample/OACodeSamples.vue'))
export const OASecurity = defineAsyncComponent(() => import('./Security/OASecurity.vue'))
export const OAOperationTags = defineAsyncComponent(() => import('./Operation/OAOperationTags.vue'))
export const OAFooter = defineAsyncComponent(() => import('./Common/OAFooter.vue'))
export const OAHeaderBadges = defineAsyncComponent(() => import('./Common/OAHeaderBadges.vue'))
