name: Publish Any Commit

on:
  push:

  pull_request:
    types: [ opened, synchronize ]

  pull_request_review:
    types: [ submitted ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install pnpm
        uses: pnpm/action-setup@v6.0.10

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: '22.13.0'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - run: pnpm dlx pkg-pr-new@0.0 publish --compact --pnpm ./
