name: Vercel Preview E2E Tests

on:
  push:

  pull_request:
    branches: [ main, develop ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-tests:
    name: Run E2E Tests on Vercel Preview
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Get Vercel Preview URL
        id: get-vercel-preview-url
        uses: ViktorJT/Get-vercel-preview-url@1.2.2
        with:
          vercel_access_token: ${{ secrets.VERCEL_ACCESS_TOKEN }}
          vercel_team_id: ${{ secrets.VERCEL_TEAM_ID }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Display Vercel Preview URL
        run: |
          echo "Vercel Preview URL: ${{ steps.get-vercel-preview-url.outputs.preview_url }}"

      - name: Run Playwright tests against Vercel Preview
        run: pnpm exec playwright test
        env:
          PLAYWRIGHT_BASE_URL: ${{ steps.get-vercel-preview-url.outputs.preview_url }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: |
            playwright-report/
            test-results/
          retention-days: 30
